package com.example.selenium.common.util;

public enum Commons {

    COMPETITOR1("COMPETITOR1"),
    COMPETITOR2("COMPETITOR2"),
    COMPETITOR3("COMPETITOR3"),
    COMPETITOR4("COMPETITOR4"),
    COMPETITOR5("COMPETITOR5"),
    COMPETITOR6("COMPETITOR6"),
    COMPETITOR7("COMPETITOR7"),
    COMPETITOR8("COMPETITOR8"),
    COMPETITOR9("COMPETITOR9"),
    COMPETITOR10("COMPETITOR10"),
    COMPETITOR11("COMPETITOR11"),
    COMPETITOR12("COMPETITOR12"),
    COMPETITOR13("COMPETITOR13"),


    CONFIG_CATEGORY_COUNTRY("COUNTRY"),
    CONFIG_CATEGORY_SEND_AMOUNT("SEND_AMOUNT"),
    CONFIG_CATEGORY_CURRENCY("CURRENCY"),
    CONFIG_CATEGORY_COUNTRY_EN_CODE("COUNTRY_EN_CODE"),
    CONFIG_CATEGORY_COUNTRY_NO_CODE("COUNTRY_NO_CODE"),
    CONFIG_CATEGORY_CURRENCY_NO_CODE("CURRENCY_NO_CODE"),
    CONFIG_CATEGORY_COUNTRY_KO_CODE("COUNTRY_KO_CODE"),
    CONFIG_CATEGORY_DELIVERY_METHOD("DELIVERY_METHOD"),
    CONFIG_CATEGORY_PAYMENT_TYPE("PAYMENT_TYPE"),
    CONFIG_CATEGORY_CENTER_CODE("CENTER_CODE"),
    CONFIG_CATEGORY_P_COUNTRY_NAME("P_COUNTRY_NAME"),
    CONFIG_CATEGORY_PAYOUT_COUNTRY("PAYOUT_COUNTRY"),

    CONFIG_CATEGORY_CONFIG("CONFIG"),
    CONFIG_CODE_MAIL("MAIL"),
    CONFIG_CODE_SMS("SMS"),
    CONFIG_CODE_PARAM_COMMON("COMMON"),

    COUNTRY_AUSTRALIA("AUSTRALIA"),
    COUNTRY_BANGLADESH("BANGLADESH"),
    COUNTRY_CAMBODIA("CAMBODIA"),
    COUNTRY_CHINA("CHINA"),
    COUNTRY_INDIA("INDIA"),
    COUNTRY_INDONESIA("INDONESIA"),
    COUNTRY_KAZAKHSTAN("KAZAKHSTAN"),
    COUNTRY_KYRGYZSTAN("KYRGYZSTAN"),
    COUNTRY_MALAYSIA("MALAYSIA"),
    COUNTRY_MYANMAR("MYANMAR"),
    COUNTRY_MONGOLIA("MONGOLIA"),
    COUNTRY_NEPAL("NEPAL"),
    COUNTRY_PAKISTAN("PAKISTAN"),
    COUNTRY_PHILIPPINES("PHILIPPINES"),
    COUNTRY_SINGAPORE("SINGAPORE"),
    COUNTRY_RUSSIA("RUSSIA"),
    COUNTRY_SRI_LANKA("SRI_LANKA"),
    COUNTRY_THAILAND("THAILAND"),
    COUNTRY_UK("UK"),
    COUNTRY_USA("USA"),
    COUNTRY_UZBEKISTAN("UZBEKISTAN"),
    COUNTRY_VIETNAM("CANADA"),
    COUNTRY_JAPAN("JAPAN"),
    COUNTRY_GERMANY("GERMANY"),
    COUNTRY_EUR("EUR"),

    RESPONSE_SUCCESS("200"),
    RESPONSE_FAIL("400");


    private String code;

    Commons(String code) {
        this.code = code;
    }

    public String CODE() {
        return code;
    }


}
